In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import csv
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
raw_primary = []
raw_secondary = []
#lines=393732;
lines=10000;
#df=pd.read_csv('PDB_CLEAN_DATA.csv')
#display(df)
with open('/content/drive/MyDrive/Protein/Kaggle/PDB_CLEAN_DATA.csv') as csv_file:
	csv_reader = csv.reader(csv_file, delimiter=',')
	line_count = 0
	for row in csv_reader:
		add = True
		if line_count == 0:
			line_count += 1
		elif line_count > lines:
			break;
		else:
			for j in range(len(row[2])):
				if row[2][j] == '*':
					#print(line_count)
					add = False
					break;
			if add == True:
				if(len(row)>=4):
					raw_primary.append( row[2] )
					raw_secondary.append( row[4] )

			line_count += 1
	print(f'Processed {line_count} lines.')

Processed 10001 lines.


In [ ]:
for i, val in enumerate(raw_primary[0:20]):
  print(str(i) + " " + val)


0 EDL
1 KCK
2 KAK
3 KFK
4 KAK
5 KMK
6 KHK
7 KIK
8 KAK
9 KGK
10 KGK
11 KFK
12 KPK
13 KAK
14 KDK
15 KSK
16 KTK
17 KYK
18 KAK
19 KNK


In [ ]:
len(raw_primary)


7366

In [ ]:
print(raw_primary)
print(len(raw_primary))

['EDL', 'KCK', 'KAK', 'KFK', 'KAK', 'KMK', 'KHK', 'KIK', 'KAK', 'KGK', 'KGK', 'KFK', 'KPK', 'KAK', 'KDK', 'KSK', 'KTK', 'KYK', 'KAK', 'KNK', 'KQK', 'KVK', 'KLK', 'FPR', 'KLK', 'MAS', 'MAS', 'MAS', 'MAS', 'MAS', 'MAS', 'APR', 'GAR', 'KAA', 'KAA', 'KAA', 'KAA', 'KAA', 'KAA', 'GAR', 'GAK', 'GAK', 'GAR', 'KAA', 'KAA', 'KAA', 'KAA', 'KAK', 'KEK', 'KWK', 'GLF', 'ENW', 'EQW', 'EKW', 'MLF', 'FPR', 'KRK', 'KVK', 'FPR', 'FPR', 'LLF', 'AIH', 'FPR', 'GAR', 'KNL', 'MAS', 'MAS', 'FPR', 'FPR', 'KKK', 'IAG', 'IAG', 'IAG', 'IAG', 'LLT', 'LLT', 'LLT', 'LLT', 'FPR', 'FPR', 'FPR', 'FPR', 'FPR', 'EGR', 'KKK', 'RSR', 'RAR', 'FPR', 'AAA', 'LLL', 'YRF', 'YQF', 'KNL', 'QLA', 'QLA', 'KGE', 'KGE', 'KGE', 'KGE', 'KGE', 'KGE', 'KGE', 'KGE', 'FPR', 'FPR', 'DVA', 'AAA', 'AAA', 'QII', 'IEI', 'MAS', 'MAS', 'AAA', 'AAA', 'AAK', 'MAS', 'MAR', 'LIA', 'GAW', 'GPRP', 'GPRP', 'GHRP', 'GHRP', 'GHRP', 'GHRP', 'GHRP', 'GHRP', 'GHRP', 'PGVY', 'PGAY', 'VEPI', 'LQES', 'TITS', 'GSNS', 'GPRP', 'GHRP', 'GPRP', 'GHRP', 'GHRP', 'RVRK'

In [ ]:
len(raw_secondary)


7366

In [ ]:
print(raw_secondary)

['CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CEC', 'CECC', 'CECC', 'CECC', 'CECC', 'CECC', 'CECC', 'CECC', 'CECC', 'CECC', 'CCEC', 'CCEC', 'CEEC', 'CECC', 'CECC', 'CCEC', 'CECC', 'CECC', 'CECC', 'CECC', 'CECC', 'CCEC'

In [ ]:
for i in range(len(raw_secondary)):
	len1 = len(raw_secondary[i])
	len2 = len(raw_primary[i])
	if(len1 != len2):
	  print(i," ", raw_secondary[i]," ",raw_primary[i])

In [ ]:
def split(sequence):
  return [char for char in sequence]


In [ ]:
split_primary = []
split_secondary = []
for i in range(len(raw_primary)):
  split_primary.append(split(raw_primary[i]))
  split_secondary.append(split(raw_secondary[i]))

In [ ]:
print(len(split_primary))
print(split_primary[:3])

7366
[['E', 'D', 'L'], ['K', 'C', 'K'], ['K', 'A', 'K']]


In [ ]:
print(len(split_primary[0:20]))
print(split_primary[0:20])

print(len(split_secondary[0:20]))
print(split_secondary[0:20])



20
[['E', 'D', 'L'], ['K', 'C', 'K'], ['K', 'A', 'K'], ['K', 'F', 'K'], ['K', 'A', 'K'], ['K', 'M', 'K'], ['K', 'H', 'K'], ['K', 'I', 'K'], ['K', 'A', 'K'], ['K', 'G', 'K'], ['K', 'G', 'K'], ['K', 'F', 'K'], ['K', 'P', 'K'], ['K', 'A', 'K'], ['K', 'D', 'K'], ['K', 'S', 'K'], ['K', 'T', 'K'], ['K', 'Y', 'K'], ['K', 'A', 'K'], ['K', 'N', 'K']]
20
[['C', 'E', 'C'], ['C', 'E', 'C'], ['C', 'E', 'C'], ['C', 'E', 'C'], ['C', 'E', 'C'], ['C', 'E', 'C'], ['C', 'E', 'C'], ['C', 'E', 'C'], ['C', 'E', 'C'], ['C', 'E', 'C'], ['C', 'E', 'C'], ['C', 'E', 'C'], ['C', 'E', 'C'], ['C', 'E', 'C'], ['C', 'E', 'C'], ['C', 'E', 'C'], ['C', 'E', 'C'], ['C', 'E', 'C'], ['C', 'E', 'C'], ['C', 'E', 'C']]


In [ ]:
def orthogonal_primary(arg):
  switch = {
  'A' : np.array([1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]),
  'C' : np.array([0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]),
  'E' : np.array([0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]),
  'D' : np.array([0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]),
  'G' : np.array([0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]),
  'F' : np.array([0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0]),
  'I' : np.array([0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0]),
  'H' : np.array([0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0]),
  'K' : np.array([0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0]),
  'M' : np.array([0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0]),
  'L' : np.array([0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0]),
  'N' : np.array([0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0]),
  'Q' : np.array([0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0]),
  'P' : np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0]),
  'S' : np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0]),
  'R' : np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0]),
  'T' : np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0]),
  'W' : np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0]),
  'V' : np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0]),
  'Y' : np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1])
  }
  return switch.get(arg)


In [ ]:
def orthogonal_secondary(arg):
  switch = {
  'H' : 0,
  'C' : 1,
  'E' : 2
  }
  return switch.get(arg)

In [ ]:
for i in range(len(split_primary)):
  seq = split_primary[i]
  for j in range(len(seq)):
    seq[j] = orthogonal_primary(seq[j])

In [ ]:
len(split_primary)

7366

In [ ]:
split_primary[0:5]


[[array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
  array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
  array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])],
 [array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
  array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
  array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])],
 [array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
  array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
  array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])],
 [array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
  array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
  array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])],
 [array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
  array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
  

In [ ]:
for i in range(len(split_secondary)):
  seq2 = split_secondary[i]
  for j in range(len(seq2)):
    seq2[j] = orthogonal_secondary(seq2[j])


In [ ]:
split_secondary[0:5]


[[1, 2, 1], [1, 2, 1], [1, 2, 1], [1, 2, 1], [1, 2, 1]]

In [ ]:
def target(lis):
  Y = []
  print(len(lis))
  for i in range(len(lis)):
    for j in range(len(lis[i])):
      Y.append(lis[i][j])
  return Y


In [ ]:
y_label = target(split_secondary)

7366


In [ ]:
y_label = np.array(y_label)
print(y_label[0:15])

[1 2 1 1 2 1 1 2 1 1 2 1 1 2 1]


In [ ]:
def window_padding_data(size, sequence):
	num = int(size/2)
	zeros = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

	for i in range(len(sequence)):
		for j in range(num):
			sequence[i].append(zeros)
			sequence[i].insert(0, zeros)
	X = []
	temp = []
	for k in range(len(sequence)):
		for l in range(len( sequence[k])-(size-1) ):
			temp = sequence[k][l:l+size]
			X.append(temp)
			temp = []
	return X

In [ ]:
X = window_padding_data(17,split_primary)


In [ ]:
len(X)


82487

In [ ]:
print(X[0])

[array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0,

In [ ]:
print(len(X[1]))

17


In [ ]:
len(y_label)


82487

In [ ]:
X = np.array(X)


In [ ]:
X.shape

(82487, 17, 20)

In [ ]:
p=X.shape
X = X.reshape(p[0], 17*20)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y_label, test_size = 0.50)
print(X_train[0])
print(X_test[0])
print(y_train[0])
print(y_test[0])
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)


[0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 

In [ ]:
svc = SVC(kernel='rbf', gamma = 0.1, C=1.5)
svc.fit(X_train, y_train)
y_pred = svc.predict(X_test)
y_true = y_test
print(classification_report(y_true,y_pred))

              precision    recall  f1-score   support

           0       0.87      0.82      0.85      3733
           1       0.92      0.96      0.94     17961
           2       0.91      0.72      0.81      3053

    accuracy                           0.91     24747
   macro avg       0.90      0.84      0.87     24747
weighted avg       0.91      0.91      0.91     24747



In [37]:
X_train, X_test, y_train, y_test = train_test_split(X, y_label, test_size = 0.50)
y_pred = svc.predict(X_test)
y_true = y_test
print(classification_report(y_true,y_pred))

              precision    recall  f1-score   support

           0       0.90      0.90      0.90      6302
           1       0.95      0.97      0.96     29882
           2       0.94      0.81      0.87      5060

    accuracy                           0.94     41244
   macro avg       0.93      0.89      0.91     41244
weighted avg       0.94      0.94      0.94     41244

